### ISSUE TITLE
Discussion around position as a point vs as two int

### ISSUE THREAD

**Issue by Yamimutu** [Ducasse/Myg#21]
We are forced to write the following because Myg stores a point. May be storing an X and Y in MygAbstractBox would be better

```
positionX: x

	position setX: x setY: position y
```

**Comment by Enzo-Demeulenaere** [comment]
This ultimately is a design choice, if we choose to keep an X and a Y, we would need to call both of these anytime we need the position of the Box, and asking the full position of the Box is done more often than setting only one of these coordinates, thus we decide to keep this implementation
