### ISSUE TITLE
MygSkElement is a bad name 

### ISSUE THREAD

**Issue by Ducasse** [Ducasse/Myg#23]
Because it is not a Bloc element but a model element. 
![Capture 2024-01-14 at 17 59 17](https://github.com/Ducasse/Myg/assets/432549/917f9671-0afa-4691-9e5e-9d344c2b021b)

**Comment by Enzo-Demeulenaere** [comment]
Renamed it to MygSkObject in commit #270f80c60f97f1a14867765a4f03410460b01704
