### ISSUE TITLE
Read menu icons with game resources manager

### ISSUE THREAD

**Issue by tinchodias** [Ducasse/Myg#6]
I propose replacing occurrences of `Smalltalk ui icons iconNamed: #anIconName` by filesystem's PNGs.

Example of an occurrence:
https://github.com/Ducasse/Myg/blob/f82bf6b4592f8b958a300c5344b2e70242d3541a/src/Myg-MineSweeper/MineSweeper.class.st#L43

WDYT?

**Comment by Ducasse** [comment]
I agree this is important not to propagate this bad idiom.
